twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        legal_documents: '%legal_documents%'
        upload_product_path: '%upload_public_path_product%'

        
when@test:
    twig:
        strict_variables: true
